cache:
  key: "$CI_COMMIT_REF_NAME/$CI_JOB_STAGE"
  paths:
    - .composer/
    - .php_cs.cache

before_script:
  - apk add git --update

stages:
  - test

test:cgl:
  image: composer:1.3
  stage: test
  before_script:
  - composer remove typo3/cms-core --no-update
  - composer install
  script:
  - .Build/bin/php-cs-fixer fix --config=Build/.php_cs -v --dry-run --using-cache=no --path-mode=intersection
